specfile_path: packaging/kcast.spec
downstream_package_name: kcast
upstream_tag_template: "v{version}"

actions:
  create-archive:
    - bash -lc 'VER=$(git describe --tags --abbrev=0 | sed "s/^v//"); git archive --format=tar --prefix=KCast-$VER/ v$VER | gzip -9 > KCast-$VER.tar.gz && echo KCast-$VER.tar.gz'
  get-current-version:
    - bash -lc "git describe --tags --abbrev=0 | sed 's/^v//'"

jobs:
  - job: copr_build
    trigger: release           # nur neue Tags/Releases
    owner: agundur
    project: KCast
    targets: ["fedora-42-x86_64"]

